### ISSUE TITLE
Unsubscribe Function Fails to Remove Event Handlers with Options

### ISSUE THREAD

**Issue by pix666** [xnimorz/subscribe-event#2]
When using the subscribe function with options like `capture: true` to create an event subscription, calling the unsubscribe function does not remove the event handler.

```javascript
handler = () => { console.log("mousedown") };
unsubscribe = subscribe(document, "mousedown", handler, { capture: true });
unsubscribe()  // <-- not working
```

**Comment by xnimorz** [comment]
Published in subscribe-event@1.1.2
